version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["bundle","exec","rails s -b 0.0.0.0"]
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    stdin_open: true
    tty: true
    environment:
      BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - iugu_bank_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: pass123

volumes:
  iugu_bank_db:
